### ISSUE TITLE
Remember that supabase development is not supported on Windows

### ISSUE THREAD

**Issue by ruggi99** [supabase/supabase.dev#1]
# Improve documentation

## Link 

No page yet

## Describe the problem

Hi @kiwicopple.
Nice to have documentation for developers.
Only to remember that developing Supabase on Windows is not supported because of this issue: https://github.com/supabase/postgres-meta/issues/387

Keep up the good work

## Describe the improvement

A clear and concise description of the improvement.

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by kiwicopple** [comment]
Thanks for reporting this @ruggi99 - I'll close it for now because this is just an experiment. We will probably end up migrating this to our main website
